### PR TITLE
Make sure all layout and scripts can be loaded over https.

### PR DESCRIPTION
**Pull request by WouterSioen**
github.io is hosted on https now, this should fix loading your stylesheets and scripts

### CODE REVIEW

**Comment by WouterSioen** [comment]
Hmm, looks like this is automatically generaged

**Comment by matthiasnoback** [comment]
Do I need to do anything? Using http:// it just works.

**Comment by WouterSioen** [comment]
When I browse to http://simplebus.github.io/MessageBus/, I get redirected to https automatically. Because of the links in the documentation pointing to http on a https domain, I get a messed up layout (using the newest chrome on a mac):

screen shot 2015-06-10 at 09 21 02

The url pointing to assets on should thus start with '//' instead of 'http://' to make sure they can be loaded over both https and http.


I have no idea how couscous works, so I can't really say how this should be fixed, but I don't think it can be a lot of work. If you point me in the right direction, I'm willing to do a pull request to fix it.

**Comment by WouterSioen** [comment]
This is the output of the Chrome dev console:

screen shot 2015-06-10 at 09 23 51

**Comment by matthiasnoback** [comment]
Right, https doesn't work, but I don't get an automatic redirect when I use http...
About the auto-generated docs, I use Couscous for this (http://couscous.io/). It doesn't look like the problem has been reported with them and I don't have the template files in my projects, so... I don't know. Maybe we wait for some more reports on this problem and try fixing it then?

**Comment by WouterSioen** [comment]
Sounds good to me :)

**Comment by matthiasnoback** [comment]
Okay, thanks again!

**Comment by jdreesen** [comment]
> Right, https doesn't work, but I don't get an automatic redirect when I use http...

I'm using the [HTTPS Everywhere](https://www.eff.org/HTTPS-everywhere) plugin, so it's broken for me  :(

**Comment by matthiasnoback** [comment]
@jdreesen Thanks for reporting! I'll see if it can be fixed in Couscous itself.

**Comment by matthiasnoback** [comment]
Okay, it appears to be pretty simple, actually. The baseUrl configuration should start with //. I'm changing this right now.

**Comment by jdreesen** [comment]
Now it's much better! Thx :)

**Comment by matthiasnoback** [comment]
Great!

**Comment by WouterSioen** [comment]
Thanks for fixing it!

**Comment by WouterSioen** [comment]
There's one problem left: the http://yastatic.net/highlightjs/8.2/highlight.min.js asset is still loaded over http. Syntax highlighting doesn't work.

**Comment by matthiasnoback** [comment]
Oh no!

**Comment by matthiasnoback** [comment]
That's more like a couscous template issue. I will make a PR for them.

**Comment by matthiasnoback** [comment]
Just did: https://github.com/CouscousPHP/Template-Light/compare/master...matthiasnoback:patch-1

**Comment by WouterSioen** [comment]
That should fix it!

**Comment by matthiasnoback** [comment]
@WouterSioen done!

**Comment by WouterSioen** [comment]
It's looking shiny now, thanks!

**Comment by matthiasnoback** [comment]
You're welcome and thanks again for reporting.

**Pull request closed without merging**
