### PR TITLE
Allow PHP 7 in Composer

### PR DESCRIPTION
**Pull request by ruudk**
See https://twitter.com/ocramius/status/658225000546238464

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for reporting :) I'm not sold yet though. I understand the reasoning behind it, but I guess that when a new major version of PHP arrives and it turns out not to be compatible, we'll fix things anyway (and don't want to prevent people from installing this package anyway). 
Now we need to update all existing packages and create new releases for something that doesn't have an effect on anybody (maybe in a few years) ;)

**Comment by ruudk** [comment]
Fair enough :)

**Comment by TomasVotruba** [comment]
Tests passes on PHP 7.0 very well. Could we at least remove redundant PHP 7.0 `allowed_failures`?

**Comment by matthiasnoback** [comment]
By all means, yes! That makes sense. That wouldn't even require a new
release.

**Comment by ruudk** [comment]
PR added!

**Comment by matthiasnoback** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
:+1: Thanks guys!

**Pull request closed without merging**
