### PR TITLE
Drop support for php 5.4 and 5.5

### PR DESCRIPTION
**Pull request by cmodijk**
I'm going to drop support for PHP 5.4 and 5.5 by the end of this month and will release the next major version by then.

All the other pull requests
- https://github.com/SimpleBus/RabbitMQBundleBridge/pull/30
- https://github.com/SimpleBus/DoctrineORMBridge/pull/8
- https://github.com/SimpleBus/DoctrineDBALBridge/pull/2
- https://github.com/SimpleBus/AsynchronousBundle/pull/12
- https://github.com/SimpleBus/Asynchronous/pull/12
- https://github.com/SimpleBus/SymfonyBridge/pull/42
- https://github.com/SimpleBus/SimpleBusBernardBundleBridge/pull/9
- https://github.com/SimpleBus/Serialization/pull/7
- https://github.com/SimpleBus/JMSSerializerBundleBridge/pull/8
- https://github.com/SimpleBus/JMSSerializerBridge/pull/5

### CODE REVIEW

**Comment by ruudk** [comment]
Why not drop everything, except 7.1 :D ?

**Comment by cmodijk** [comment]
> Why not drop everything, except 7.1 :D ?

That is a good question. PHP 5.6 is stil in security support until '31 Dec 2018' and php 7.0 is still supported. But i'm open to more opinions about this subject. If more people think we should stop supporting the 5.6 and 7.0 i'm open for that.

**Comment by ruudk** [comment]
I think that people who use these kind of stuff are not in old versions of PHP ;)

**Comment by cmodijk** [comment]
I'm a bit ashamed our project is stil 5.6

**Pull request merged**
