### PR TITLE
Reuse trait instead of duplicating code

### PR DESCRIPTION
**Pull request by borNfreee**

### CODE REVIEW

**Comment by jdreesen** [comment]
Be careful, the `record()` method is `protected` in the trait and `public` the class.
I think that's the reason one is named **Private**MessageRecorderCapabilities and the other one **Public**MessageRecorder.

**Comment by jdreesen** [comment]
I don't think simply changing the method's visibility to `public` in the trait is the way to go here.

**Comment by jdreesen** [comment]
I'm not using traits much... but maybe leaving the method `protected` in the trait and using it with 
```php
use PrivateMessageRecorderCapabilities { record as public; }
```
 would work?

**Comment by borNfreee** [comment]
I agree with you notices, but let's have a look at the documentation: http://simplebus.github.io/MessageBus/doc/message_recorder.html

```php
class YourEntity implements RecordsMessages
{
...
}
```

The documentation says that `Entity` implements the interface `RecordsMessages` which has (obviously) a public method `records`, which is completely compatible with what I have changed

**Comment by borNfreee** [comment]
@jdreesen yeah, looks like a good solution. Let's wait the travis build

**Comment by jdreesen** [comment]
Oh, you are right, but I think the docs are wrong here because the section describes privately recording messages (which is generally what you want to do in a domain entity - it should be able to record it's own messages, but no one else should be allowed to do this).

**Comment by borNfreee** [comment]
@jdreesen ok, with changing the visibility just for used trait it looks good. What do you think?

//cc @matthiasnoback

**Comment by jdreesen** [comment]
I'm no maintainer of this project, and no great fan of traits, but as the trait exists anyways and differs with the class only in the visibility of one method I think this seems like a valid approach. 
But the docs should be corrected, too.

**Comment by matthiasnoback** [comment]
Hi everyone, I'm sure @cmodijk was going to reply but I saw that passing by and thought it was an interesting suggestion - I didn't know PHP had the option to change visibility of trait methods when used, so... this would be a win-win situation I think. You don't always have to be DRY about everything, but in this case the implementation is not only accidentally the same, it is supposed to be the same. Thanks!

**Comment by cmodijk** [comment]
@borNfreee @jdreesen @matthiasnoback Tnx for the discussion i never new this was possible with traits. I just merged this in the code bases tnx!

**Pull request merged**
